version: '3'
networks:
  laravel-network:
    driver: bridge
services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8003:80" # Change this line
    volumes:
      - ./lara_api:/var/www/html
    depends_on:
      - mysql
    networks:
      - laravel-network
  mysql:
    image: mysql:5.7
    ports:
      - "3309:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: rss_db
      MYSQL_PASSWORD: root
    networks:
      - laravel-network
  vue:
    build:
      context: ./vue-app
      dockerfile: Dockerfile
    ports:
      - "8082:8080"
    networks:
      - laravel-network
